Repository seung-lab/cloud-files, pull requests merged in 2021-12, with the labels that each got.

#70 feat: s3 aliases
  README.md
  automated_test.py
  cloudfiles/cloudfiles.py
  cloudfiles/connectionpools.py
  cloudfiles/interfaces.py
  cloudfiles/paths.py
  cloudfiles_cli/cloudfiles_cli.py
Labels: feature, CLI

#72 feat: support listing on https://storage.googleapis.com/
  cloudfiles/interfaces.py
Labels: feature

#73 fix(S3Interface): release_connection respects alias
  cloudfiles/interfaces.py
Labels: bug
